TWITTER_CONSUMER_KEY = 'a1gmxVNt1N2I3Yhptmw5etIDh'
TWITTER_CONSUMER_SECRET = 'J8aIMLoyCqs8jTYiPCPtNZrJF57CE76hYZd2jR8o7zBmI6reIi'
TWITTER_ACCESS_TOKEN = '105418313-jgWx5ZGkfp6xE0ckC8yuzBhyWLMOKNRXuSk8eOEJ'
TWITTER_ACCESS_TOKEN_SECRET = 'WWmg3H8H91XT0V7cjO5lXBUQu5kTgWZCusABGVj9qqgq8'

#TWITTER_CLIENT_ID = 'LVJTbkxNeWVwTEJRVnp5cGFGcnI6MTpjaQ'
#TWITTER_CLIENT_SECRET = '2Gnpie7reNMmzcuiNsHrbS8ET8W2GgEfKVhqHoiePQJ3KmL9ME'

TWITTER_USERNAMES = [
    'traderstewie',
    'the_chart_life',
    'canuck2usa',
    'sunrisetrader',
    'tmltrader'
]

DB_HOST = 'localhost'
DB_USER = 'postgres'
DB_PASS = 'Test1234'
DB_NAME = 'stockdb'

API_KEY_FMP = '14afe305132a682a2742743df532707d'

EXCLUDED_INDUSTRIES_TA = [
    'Financial - Investment Funds',
]

STLOUISFED_SERIES = ['A072RC1Q156SBEA',	
    'DPCCRV1Q225SBEA',	
    'EXPGSC1',
    'GCEC1',	
    'GDPC1',	
    'GDPCTPI',	
    'GPDIC1',	
    'IMPGSC1',	
    'JCXFE',	
    'PCECC96',
    'CIVPART',	
    'PAYEMS',	
    'UNRATE',
    'CCSA',	
    'ICSA',
    'PCEPI',	
    'PCEPILFE',	
    'DFEDTARU',	
    'CPIAUCSL',	
    'CPIENGSL',	
    'CPIFABSL',	
    'CPILFESL',
    'INDPRO',
    'IPB54100S',	
    'IPBUSEQ',	
    'IPCONGD',	
    'IPMAN',	
    'IPMAT',	
    'IPMINE',	
    'IPUTIL',	
    'TCU',	
    'WPSFD4131',
    'A31SNO',	
    'A32SNO',	
    'A33SNO',	
    'A34SNO',	
    'A35SNO',	
    'A36SNO',	
    'ADXDNO',	
    'ADXTNO',	
    'AMTUNO',	
    'ANXAVS',	
    'DGORDER',	
    'NEWORDER',
    'MARTSSM44W72USS',	
    'RSAFS',	
    'RSBMGESD',	
    'RSCCAS',	
    'RSDBS',	
    'RSEAS',	
    'RSFHFS',	
    'RSFSDP',	
    'RSFSXMV',	
    'RSGASS',	
    'RSGMS',	
    'RSHPCS',	
    'RSMSR',	
    'RSMVPD',	
    'RSNSR',	
    'RSSGHBMS',
    'INTDSRUSM193N',	
    'FEDFUNDS',	
    'DPCREDIT',
    'WALCL',
    'JPNASSETS',	
    'JPNNGDP',	
    'ECBASSETSW',
    'BOPGSTB',
    'M1REAL',	
    'M2REAL',	
    'M2SL',	
    'M2V',
    'COMPUTSA',	
    'HOUST',	
    'PERMIT'
]

STLOUISFED_SERIES_DEBUG = ['A072RC1Q156SBEA']

YF_ETF_SERIES = [
    'AGG', 
    'BIL', 
    'DJP', 
    'DX-Y.NYB', 
    'EEM', 
    'EFA', 
    'GC=F', 
    'HYG', 
    'IBB', 
    'IWM', 
    'MDY', 
    'QQQ', 
    'RXI', 
    'SPY', 
    'TIP', 
    'USO', 
    'VNQ', 
    'XLB', 
    'XLC', 
    'XLE', 
    'XLF', 
    'XLI', 
    'XLK', 
    'XLP', 
    'XLRE', 
    'XLU',
    'XLV', 
    'XLY', 
    'ACWI', 
    'ARGT', 
    'BAL', 
    'BJK', 
    'CORN', 
    'COW', 
    'CUT', 
    'DIA', 
    'ECH', 
    'EDEN', 
    'EFNL', 
    'EGPT', 
    'EIRL', 
    'EIS', 
    'ENZL', 
    'EPHE', 
    'EPOL', 
    'EPU', 
    'EWA', 
    'EWC', 
    'EWD', 
    'EWG', 
    'EWH', 
    'EWI', 
    'EWJ', 
    'EWK', 
    'EWL', 
    'EWM', 
    'EWN', 
    'EWO', 
    'EWP', 
    'EWQ', 
    'EWS', 
    'EWT', 
    'EWU', 
    'EWW', 
    'EWY', 
    'EWZ', 
    'EXH1.DE', 
    'EXH2.DE', 
    'EXH3.DE', 
    'EXH4.DE', 
    'EXH5.DE', 
    'EXH6.DE',
    'EXH7.DE', 
    'EXH8.DE', 
    'EXH9.DE', 
    'EXI5.DE', 
    'EXSA.DE', 
    'EXV1.DE', 
    'EXV2.DE', 
    'EXV3.DE', 
    'EXV4.DE', 
    'EXV5.DE',
    'EXV6.DE', 
    'EXV7.DE', 
    'EXV8.DE', 
    'EXV9.DE', 
    'EZA', 
    'FDN', 
    'FXI', 
    'GDX', 
    'GLD', 
    'GREK', 
    'GXG', 
    'HACK', 
    'IAI', 
    'IDU', 
    'IDX', 
    'IGN', 
    'IHE', 
    'IJH', 
    'IJJ', 
    'IJK', 
    'IJR', 
    'IJS', 
    'IJT', 
    'INDY', 
    'IVE', 
    'IVW', 
    'IWC', 
    'IWD', 
    'IWF', 
    'IWN', 
    'IWO', 
    'IWP', 
    'IWS', 
    'IWV', 
    'IYR', 
    'IYT', 
    'IYZ', 
    'JETS', 
    'JJC', 
    'JJG', 
    'JJN', 
    'JJU', 
    'JO', 
    'KBE', 
    'KIE', 
    'KOL', 
    'KRE', 
    'MOO', 
    'NGE', 
    'NORW', 
    'OEF', 
    'OIH', 
    'PALL', 
    'PBJ', 
    'PBS', 
    'PEY', 
    'PFM', 
    'PGAL', 
    'PHO', 
    'PWV', 
    'SEA', 
    'SGG', 
    'SKYY', 
    'SLV', 
    'SLX', 
    'SMH', 
    'SOCL', 
    'SOYB',
    'TAN', 
    'THD', 
    'TLT', 
    'TUR', 
    'UGA', 
    'UNG', 
    'UUP', 
    'VNM', 
    'VTV', 
    'VUG', 
    'WEAT', 
    'WOOD', 
    'XAR', 
    'XHB', 
    'XHE', 
    'XHS', 
    'XME', 
    'XRT', 
    'XSW', 
    'XTN', 
    '000300.SS', 
    '0P0001GY56.F', 
    '^AXJO', 
    '^BSESN', 
    '^DJI', 
    '^FCHI', 
    '^FTSE', 
    '^GDAXI', 
    '^GSPC', 
    '^GSPTSE', 
    '^HSI', 
    '^IBEX', 
    '^IXIC', 
    '^MXX', 
    '^N225', 
    '^NSEI', 
    '^NYA', 
    '^STOXX50E',
    'SPSM',
]

RENAME_ETF = {
    'rxi':'Consumer Discretionary (RXI)',
    'xlp':'Cons. Staples (XLP)',
    'xly':'Cons. Discret (XLY)',
    'xle':'Energy (XLE)',
    'xlf':'Financials (XLF)',
    'xlv':'Health Care (XLV)',
    'xli':'Industrials (XLI)',
    'xlk':'IT (XLK)',
    'xlb':'Materials (XLB)',
    'xlre':'Real Estate (XLRE)',
    'xlc':'Telco. (XLC)',
    'xlu':'Utilities (XLU)',
    'spy':'S&P 500 (SPY)',
    'uso':'Oil (USO)',
    'qqq':'Nasdaq 100 (QQQ)',
    'iwm':'Russell 2000 (IWM)',
    'ibb':'Nasdaq Biotech (IBB)',
    'eem':'Emerging Market (EEM)',
    'hyg':'High Yield (HYG)',
    'vnq':'REITS (VNQ)',
    'mdy':'Mid Cap (MDY)',
    'spsm':'Small cap (SPSM)',
    'efa':'International Stocks (EFA)',
    'tip':'TIPS (TIP)',
    'agg':'Bonds (AGG)',
    'djp':'Commo (DJP)',
    'bil':'Cash (BIL)',
    'gc_f':'Gold (GC=F)',
    'dx_y_nyb':'Dollar Index (DX-Y.NYB)',
    '_dji': 'Dow Jones Industrial Average',
    '_gspc': 'S&P 500 Index',
    '_ixic': 'Nasdaq Composite Index',
    '_nya': 'NYSE Composite Index',
    '_gsptse': 'S&P/TSX Composite Index (Canada)',
    '_mxx': 'IPC Mexico',		
    '_stoxx50e': 'Euro Stoxx 50 Pr (EU)',
    '_ftse': 'FTSE 100 Index (U.K.)',
    '_gdaxi': 'DAX Index (Germany)',
    '_fchi': 'CAC 40 Index (France)',
    '_ibex': 'IBEX 35 Index (Spain)',
    '_n225': 'Nikkei 225 (Japan)',
    '_hsi': 'Hang Seng Index (Hong Kong)',
    'yf_000300_ss': 'CSI 300 Index (China)',
    '_axjo': 'S&P/ASX 200 Index (Australia)',
    'yf_0P0001GY56_f': 'MSCI AC Asia Pacific',
    '_bsesn': 'BSE SENSEX (India)',
    '_nsei': 'Nifty 50 (India)',    
}

REGIONS_AMERICAS = [
    'US',
    'Canada',
    'North America',
    'South America',
    'Americas',
    'U.S',
    'United States',
    'Latin America',
    'Mexico',
    'LATAM',
    'Brazil',
    'Argentina',
]

REGIONS_ASIA_PACIFIC = [
    'Asia',
    'China',
    'Taiwan',
    'Japan',
    'Korea',
    'Asia Pacific',
    'Australia',
    'Australasia',
    'APAC',
    'India',
]

REGIONS_EUROPE_MIDDLEEAST_AFRICA = [
    'Europe',
    'Middle East',
    'Africa',
    'EMEA',
    'Bahrain',
    'Belgium',
    'United Kingdom',
    'France',
    'Germany',
    'Italy',
    'U.K'
]

#REGIONS_ALL = [
#    'Asia',
#    'Europe',
#    'US',
#    'Canada',
#    'Middle East',
#    'Africa',
#    'North America',
#    'South America',
#    'China',
#    'Taiwan',
#    'Japan',
#    'Korea',
#    'Americas',
#    'Asia Pacific',
#    'EMEA',
#    'U.S',
#    'United States',
#    'Latin America',
#    'Asia Pacific',
#    'Australia',
#    'Australasia',
#    'Mexico',
#    'LATAM',
#    'APAC',
#    'Bahrain',
#    'Brazil',
#    'Belgium',
#    'United Kingdom',
#    'Argentina',
#    'France',
#    'Germany',
#    'Italy',
#    'India',
#    'U.K'
#]