TWITTER_CONSUMER_KEY = 'a1gmxVNt1N2I3Yhptmw5etIDh'
TWITTER_CONSUMER_SECRET = 'J8aIMLoyCqs8jTYiPCPtNZrJF57CE76hYZd2jR8o7zBmI6reIi'
TWITTER_ACCESS_TOKEN = '105418313-jgWx5ZGkfp6xE0ckC8yuzBhyWLMOKNRXuSk8eOEJ'
TWITTER_ACCESS_TOKEN_SECRET = 'WWmg3H8H91XT0V7cjO5lXBUQu5kTgWZCusABGVj9qqgq8'

#TWITTER_CLIENT_ID = 'LVJTbkxNeWVwTEJRVnp5cGFGcnI6MTpjaQ'
#TWITTER_CLIENT_SECRET = '2Gnpie7reNMmzcuiNsHrbS8ET8W2GgEfKVhqHoiePQJ3KmL9ME'

TWITTER_USERNAMES = [
    'traderstewie',
    'the_chart_life',
    'canuck2usa',
    'sunrisetrader',
    'tmltrader'
]

DB_HOST = 'localhost'
DB_USER = 'postgres'
DB_PASS = 'Test1234'
DB_NAME = 'stockdb'